spring:
  application:
    name: 04.sb-security-db-users
  datasource:
    url: jdbc:mysql://localhost:3306/db_fidelity
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
