spring:
  application:
    name: 03.sb-data-finders
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_fidelity
    username: root
    password: root
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: error
    com:
      fidelity: debug
  file:
    name: ./logs/app.log
        